labelsForCities = [
  // "Boston city",
  "Worcester city",
  "Springfield city",
  "Lowell city",
  "Cambridge city",
  "NewBedford city",
  "Brockton city",
  "Quincy city",
  "Lynn city",
  "FallRiver city",
  "Newton city",
  "Lawrence city",
  "Somerville city",
  "Framingham town",
  "Haverhill city",
  "Waltham city",
  "Malden city",
  "Brookline town",
  "Plymouth town",
  "Medford city",
  "Taunton city",
  "Chicopee city",
  "Weymouth town city",
  "Revere city",
  "Peabody city",
  "Methuen town city",
  "Barnstable town city",
];
